# Generated by Django 2.2.7 on 2019-11-29 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterwatchapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterconsumption',
            name='DateTime',
        ),
    ]
